In [ ]:
import numpy as np

# Set random seed
np.random.seed(12)

# Create random matrix A
A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)

# Reduce A to its Row Echelon Form
def reduce_to_row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return matrix
        matrix[[i, r]] = matrix[[r, i]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(m):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] = matrix[i] - lv * matrix[r]
        lead += 1
    return matrix

row_echelon_A = reduce_to_row_echelon_form(A.copy())
print("\nRow Echelon Form of A:")
print(row_echelon_A)

Matrix A:
[[6 1 2 3 3]
 [0 6 1 4 5]
 [9 2 6 0 5]
 [8 2 9 3 4]
 [3 1 7 0 2]]

Row Echelon Form of A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
