In [ ]:
import numpy as np

# Given matrix A
A = np.array([[6, 1, 2, 3, 3],
              [0, 6, 1, 4, 5],
              [9, 2, 6, 0, 5],
              [8, 2, 9, 3, 4],
              [3, 1, 7, 0, 2]])

# Perform Singular Value Decomposition
U, sigma, Vt = np.linalg.svd(A)

# Create Σ matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape), :min(A.shape)] = np.diag(sigma)

# Verify A equals the product of U, Σ, and Vt
A_reconstructed = np.dot(U, np.dot(Sigma, Vt))
print("\nIs A equal to the product of U, Σ, and Vt? ", np.allclose(A, A_reconstructed))

# Separate and print matrices U, Σ, and V
print("\nMatrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix V:")
print(Vt.T)

# Rank 2 and rank 3 approximations of matrix A
rank_2_approx = np.dot(U[:, :2], np.dot(Sigma[:2, :2], Vt[:2, :]))
rank_3_approx = np.dot(U[:, :3], np.dot(Sigma[:3, :3], Vt[:3, :]))

print("\nRank 2 approximation of matrix A:")
print(rank_2_approx)
print("\nRank 3 approximation of matrix A:")
print(rank_3_approx)


Is A equal to the product of U, Σ, and Vt?  True

Matrix U:
[[-0.33704536 -0.09852066  0.60880433  0.44567731 -0.55445751]
 [-0.22149094 -0.95077012 -0.17140968 -0.13234754  0.0089885 ]
 [-0.56718927  0.17189631  0.34185894 -0.72094124  0.11010984]
 [-0.63060082  0.11979293 -0.21214348  0.50591034  0.53576313]
 [-0.3434838   0.20598828 -0.66189396 -0.09030127 -0.62716008]]

Matrix Σ:
[[20.68661882  0.          0.          0.          0.        ]
 [ 0.          7.88617047  0.          0.          0.        ]
 [ 0.          0.          4.72636203  0.          0.        ]
 [ 0.          0.          0.          2.7330212   0.        ]
 [ 0.          0.          0.          0.          0.25340525]]

Matrix V:
[[-0.63820162  0.32110022  0.64462407 -0.01391445  0.27177112]
 [-0.21294224 -0.63576797 -0.17394283 -0.31787936  0.64741894]
 [-0.59838253  0.30478935 -0.72893198  0.12968934 -0.02967559]
 [-0.18315716 -0.47415456  0.10670867  0.8508433  -0.07943457]
 [-0.39464681 -0.4182997   0.1071